### ISSUE TITLE
Не работают баттлы.

### ISSUE THREAD

**Issue by alexsprokosin** [Erder00/royale-brawl#1]
Здравствуйте! у меня причина такая я вхожу в бой а у меня зависает на 100% и всё.

https://github.com/user-attachments/assets/469f62f6-7b9c-40ce-a85a-9453f8ef7fa2

вот

**Comment by Erder00** [comment]
try restarting the server, if that doesn't work try running it under linux and not windows.

**Comment by alexsprokosin** [comment]
Thank you, I restarted the server, checked whether I entered the IP address correctly everywhere and rewrote it and everything worked!

**Comment by alexsprokosin** [comment]
and, now create offers?

**Comment by Erder00** [comment]
> and, now create offers?

there is no json or config file for that, you'll have to code them yourself
