### ISSUE TITLE
now changed other brawler on start?

### ISSUE THREAD

**Issue by alexsprokosin** [Erder00/royale-brawl#2]
how do I make sure that I don't get standard brawlers, but only those that have been added to the client?

**Comment by alexsprokosin** [comment]
and your add offers?

**Comment by alexsprokosin** [comment]
I just noticed that there are daily promotions in the store

**Comment by alexsprokosin** [comment]
![Screenshot_2024-09-18-14-46-24-777_com cb brawlstars v36](https://github.com/user-attachments/assets/a6cb3f9c-bbd7-4482-afea-63d779d76c3d)
Can these shares be changed?

**Comment by alexsprokosin** [comment]
![photo_2024-09-21_13-43-58](https://github.com/user-attachments/assets/5113bbb2-a4c8-4bcd-a57e-309ddf41daa4)
Can these shares be changed?

**Comment by Erder00** [comment]
>  Can these shares be changed?

yes
