### ISSUE TITLE
port changer??

### ISSUE THREAD

**Issue by WhundAlt** [Erder00/royale-brawl#3]
is there anyway to change port for apk?

**Comment by Erder00** [comment]
no, and you shouldn't

**Comment by WhundAlt** [comment]
why?

**Comment by Erder00** [comment]
> why?

is it possible? no, xeon didn't include support for it in the script

why you shouldn't? because there is no reason to, 9339 for tcp and 9449 for udp. it's  good and there is no reason to change it

**Comment by WhundAlt** [comment]
so what are the files that involve major, minor and build so i can use another version that does support port?? (v27.269.1)

**Comment by Erder00** [comment]
> so what are the files that involve major, minor and build so i can use another version that does support port?? (v27.269.1)

Supercell.Laser.Logic/GameVersion.cs

**Comment by WhundAlt** [comment]
but, how do i add minor (.1) so i can change the version, in what file(s)?

**Comment by sav365** [comment]
> > why?
> 
> is it possible? no, xeon didn't include support for it in the script
> 
> why shouldn't you? because there is no reason to, 9339 for tcp and 9449 for udp. it's good and there is no reason to change it

 I was able to add port support to the apk, yay😁

**Comment by sav365** [comment]
> yes i just found it some time ago :)

Где?

**Comment by WhundAlt** [comment]
in erder00 frida scripts
